config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :destroy, :show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]

  resources :videos, only: [:show, :index] do
    resources :tracks, only: [:new, :edit, :destroy, :create, :update]
  end

  resources :languages, only: [:show] 

  root 'welcome#index'

end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :tracks
end

app/models/search.rb
class Search

  #!/usr/bin/ruby

  # Set DEVELOPER_KEY to the API key value from the APIs & auth > Credentials
  # tab of
  # {{ Google Cloud Console }} <{{ https://cloud.google.com/console }}>
  # Please ensure that you have enabled the YouTube Data API for your project.
  DEVELOPER_KEY = ENV['ENV_YOUTUBE_API']
  YOUTUBE_API_SERVICE_NAME = 'youtube'
  YOUTUBE_API_VERSION = 'v3'

  def self.get_service
    client = Google::APIClient.new(
      :key => DEVELOPER_KEY,
      :authorization => nil,
      :application_name => 'soundscript',
      :application_version => '1.0.0'
    )
    youtube = client.discovered_api(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION)

    return client, youtube
  end

  def self.main(search_term)
    opts = Trollop.options do
      opt :q, 'Search term', :type => String, :default => search_term
      opt :max_results, 'Max results', :type => :int, :default => 28
    end

    client, youtube = get_service

    begin
      # Call the search.list method to retrieve results matching the specified
      # query term.
      search_response = client.execute!(
	:api_method => youtube.search.list,
	:parameters => {
	  :part => 'snippet',
	  :q => opts[:q],
	  :maxResults => opts[:max_results]
	}
      )

      videos = []


      # Add each result to the appropriate list, and then display the lists of
      # matching videos, channels, and playlists.


    rescue Google::APIClient::TransmissionError => e
      puts e.result.body
    end

    return search_response.data.items
  end

  def self.video_by_id(id)

    opts = Trollop::options do
      opt :id, id, :type => String, :default => id
    end

    client, youtube = get_service

    begin
      # Call the search.list method to retrieve results matching the specified
      # query term.
      search_response = client.execute!(
	:api_method => youtube.videos.list,
	:parameters => {
	  :part => 'snippet',
	  :id => opts[:id]
	}
      )


    rescue Google::APIClient::TransmissionError => e
      puts e.result.body
    end

    return search_response.data.items
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
	belongs_to :user
	belongs_to :language


	def upVote
	  vote = self.vote_count += 1
	  self.save
	end

	def downVote 
	  vote = self.vote_count -= 1
	  self.save
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tracks, dependent: :destroy
	validates :username, presence: true
	validates :email, presence: true, uniqueness: true, format: {with: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\Z/i}
	validates :password_digest, presence: true

	has_secure_password


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

 def show
	 	@languages = Language.all
    @language = Language.find_by_title(params[:language])
    @tracks = Track.where(language_id: @language.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@languages = Language.all
	end


	def create
		@languages = Language.all
		@user = User.find_by_email(params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			@error = "Logged in Successfully"
			session[:user_id] = @user.id
			redirect_to root_path
		else
			@error = "Your email and password do not match."
			redirect_to new_session_path
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def create
    @languages = Language.all
    language = Language.find_by_title(params[:languagename])
    track = Track.new(youtube_id: params[:video_id], user_id: session[:user_id])
    track.transcript = params[:data].to_json
    track.language_id = language.id

    track.save
    redirect_to '/'
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to root_path
  end

  def update

    if params[:vote]
      if params[:vote].include?('up')
	track = Track.find(params[:id])
	track.upVote
      elsif params[:vote].include?('down')
	track = Track.find(params[:id])
	track.downVote
      end
    end

    if params[:languagename]
      language_id = Language.find_by_title(params[:languagename]).id
      Track.find(params[:id]).update_attributes(language_id: language_id, transcript: params[:data].to_json)
    end
    redirect_to '/'

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
include SessionsHelper
	def new
		@languages = Language.all
		@user = User.new
	end

	def create
		@languages = Language.all
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@languages = Language.all
		if current_user == User.find(params[:id])
			@user = current_user
			render 'edit'
		else
			redirect_to root_path
		end

	end

	def show
		@languages = Language.all
		if current_user == User.find(params[:id])
			@user = current_user
			render 'show'
		else
			redirect_to root_path
		end
	end

	def update
		if current_user == User.find(params[:id])
			current_user.update(user_params)
			redirect_to user_path(current_user)
		else
			redirect_to root_path
		end
	end

	def destroy

		User.find(params[:id]).destroy
		session.clear
		redirect_to root_path
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  
  def show
    @video = Search.video_by_id(params[:id]).first
    @tracks = Track.where('youtube_id=?', @video.id).order('vote_count DESC')
    @languages = Language.all
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	require 'will_paginate/array'
  def index
  	@languages = Language.all
  	@videos = Search.main(params[:search_term]).paginate(:page => params[:page], :per_page => 16)
  end
end	

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		if session[:user_id]
			@current_user ||= User.find(session[:user_id])
		end
	end
end

app/views/languages/show.html.erb
<h1>hi</h1>

<div class="container_language">

	<div id="search_language">
<table style="width:710px">
<h1><%=@language.title%></h1>
		<thead>
      <tr>
        <th>Title</th>
        <th>Created On</th>
        <th>Video</th>
      </tr>
    <thead>
  	<tbody>
			
			<% @tracks.each do |track|%>
			<% video = track.youtube_id %>
			<% videos = Search.video_by_id(video) %>
      <tr>
				<%videos.each do |vid|%>
	        <td><a href="/videos/<%=track.youtube_id%>"><%=vid.snippet.title%></a></td> 
	        
	        <td><%=track.created_at.strftime("%m/%d/%Y")%></td>
	     		<td><a href="/videos/<%=track.youtube_id%>"><img src='<%=vid.snippet.thumbnails.default.url%>'></a></td>
	        
				<%end%>
			<%end%>
        </tr>
    </tbody>
  </table>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soundscript</title>
	<link rel="shortcut icon" href="assets/logo_tab.png" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/themes/smoothness/jquery-ui.css" />
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"></script>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>

  <%= csrf_meta_tag %>
	<%= javascript_tag "var AUTH_TOKEN = '#{form_authenticity_token}';" if protect_against_forgery? %>


</head>
		
<body>
		<nav>
			<ul>
				<a href="/"><li class="soundscript_logo"></li></a>
				<%if current_user%>
					<li class="nav_link"><%= link_to "Logout", session_path(current_user), data: { confirm: "Are you sure?" }, method: "delete" %>	</li>
					<li class="nav_link"><%= link_to "Profile", user_path(current_user) %></li>	
				<%else%>
					<li class="nav_link"><%= link_to "Sign Up", new_user_path %></li>
					<li class="nav_link"><%= link_to "Log In", new_session_path %></li>
				<%end%>
				<li class="nav_link">
					<form id="form_nav" action='/' method='GET'>
						<input type='text' name='search_term' placeholder='Search'>
						<input type='submit', value='Search'>
					</form>
				</li>
				<li class="nav_link">
					<form id="search_language_form"  action="/languages/show" method="get">
						
						<input type='submit', value='search tracks by language'>
					</form>
				</li>
			</ul>
		</nav>
		<%= yield %>
</body>
</html>

app/views/users/_form.html.erb
<%=form_for @user,:html => {:class => "loginform"} do |f| %>
	<%= f.label :username %>
	<%= f.text_field :username %><br><br>

	<%= f.label :email %>
	<%= f.text_field :email %><br><br>
	
	<%= f.label :password %>
	<%= f.password_field :password %><br><br>
	
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %><br><br>

	<%= f.submit "Create Me!", :class => "submit" %>
	<%end%>

app/views/users/edit.html.erb
<div class='container'>
	<div class='login_form'>
		<%=form_for(@user,:html => {:class => "loginform"}) do |f| %>
			<%= f.label :email %>
			<%= f.text_field :email %><br>

			<%= f.label :password %>
			<%= f.password_field :password %><br>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %><br><br>

			<%= f.submit "Update!", :class => "submit" %>
			<%end%>

			<p><%= button_to "Delete Profile", user_path(current_user), method: :delete, data: { confirm: "Are you sure?" } %></p>
	</div>
</div>

app/views/users/new.html.erb
<div class="container">
	<div class="login_form">

		<%= render "form" %>
		
	</div>
</div>

app/views/users/show.html.erb
<div id="profile_container">

<h1>Hello, <%=current_user.username%>! </h1>
  <span id="edit_profile_span"><%= link_to "Edit Profile", edit_user_path(current_user), id:"edit_profile" %></span>
     <p>Email: <%=current_user.email%></p>
<h2>Videos Transcribed</h2>
<table style="width:710px">
		<thead>
      <tr>
        <th>Title</th>  
        <th>Created On</th>
        <th>Video</th>
        <th>Language</th>
        <th>Edit/Delete</th>
      </tr>
    <thead>
  	<tbody>
			<% current_user.tracks.each do |track|%>
			<% video = track.youtube_id %>
			<% videos = Search.video_by_id(video) %>
      <tr>
				<%videos.each do |vid|%>
	        <td><a href="/videos/<%=track.youtube_id%>"><%=vid.snippet.title%></a></td>    
	        <td><%=track.created_at.strftime("%m/%d/%Y")%></td>
	     		<td><a href="/videos/<%=track.youtube_id%>"><img src='<%=vid.snippet.thumbnails.default.url%>'></a></td>
	        <td><%=track.language.title%></td>
	        <td><%=button_to "Delete Track", video_track_path(vid.id, track.id), method: :delete, data: {confirm: "are you sure?"}%></td>
				<%end%>
			<%end%>
        </tr>
    </tbody>
  </table>
</div>



   

app/views/videos/show.html.erb
<div class='videoShowContainer'>
	<div class='video_box'>
		<div id="ytapiplayer">
	  	You need Flash player 8+ and JavaScript enabled to view this video.
		</div>
	</div>
	<div class='controls_box'>
		<p><%= @video.snippet.title%></p>
		<div><span id="totalDuration">--:--</span></div>
		<button class="control" id="replay" onclick="javascript:ytplayer.seekTo(0)"></button>
		<button class="control" id="play" onclick="javascript:playPauseVideo(ytplayer)"></button>
		<button class="control" id="rewind" onclick="javascript:ytplayer.seekTo(ytplayer.getCurrentTime() - 5)"></button>
		<div id="button_add_track"><button class="appendTrack">Add Track</button></div>
	</div>
	<div class='clearfix'></div>
	<div class="track_divs"></div>
</div>





<script>
	var VIDEOAPP = {
		videoId: '<%= @video.id %>',
		loggedIn: <%= current_user.present? %>,
	  languages: <%= raw @languages.to_json %>
	}

<% if @tracks.any? %>
	var transcriptJson,
		tracks = [],
		track = {},
		notes = [];

	<% @tracks.each do |trackBuild| %>
			track = {};
			notes = [];
			transcriptJson = <%= raw trackBuild.transcript %>;
			track.creatorId = <%= trackBuild.user_id %>;
			track.trackId = <%= trackBuild.id %>;
			track.language = '<%= Language.find(trackBuild.language_id).title %>';
			track.videoId = '<%= @video.id %>';
			if (transcriptJson) {
				$.each(transcriptJson, function(key, value) {	
					var note = {};
	 				note.content = value.content;
	 				note.position_css = value.position_css;
	 				notes.push(note);
				});
			}
 			track.transcriptions = notes;
 			tracks.push(track)
	<% end %>
	VIDEOAPP.tracks = tracks;
<% else %>
	VIDEOAPP.tracks = "";
<% end %>
</script>



<script type="text/javascript">
	var params = { allowScriptAccess: "always" };
	var atts = { id: "myytplayer" };
	var videoURL = "http://www.youtube.com/v/" + VIDEOAPP.videoId + "?enablejsapi=1&playerapiid=ytplayer&version=3";
  var tracksContainer;

  <% if current_user%>
		var currentUserId = <%=current_user.id%>;
	<%else%>
		var currentUserId = 0;
	<%end%>
	
	swfobject.embedSWF(videoURL,"ytapiplayer", "640", "321", "8", null, null, params, atts);

  function onYouTubePlayerReady(playerId) {
    ytplayer = document.getElementById("myytplayer");
    var vidDuration = ytplayer.getDuration();
    
    VIDEOAPP.duration = vidDuration;
  	tracksContainer = new TracksContainer(VIDEOAPP.duration, VIDEOAPP.loggedIn, VIDEOAPP.tracks, currentUserId);

    setInterval(
    	function () {
  			var currTime = Number(ytplayer.getCurrentTime()).toFixed(2);
  			var duration = Number(vidDuration).toFixed(2);
  			var wrapper = $('.trackWrapper');

	    	if (ytplayer.getPlayerState() === 1) {
		    	wrapper.animate({scrollLeft: currTime * 160},249);
		    	tracksContainer.updateHTML("totalDuration", currTime, duration);   
				}
    	}
    , 250 );
  }
</script>

app/views/welcome/index.html.erb
<div class="container">
	<div id="index_page_container">
		<div id="search_form">
			<form action='/' method='GET'>
				<input type='text' name='search_term' placeholder='  Search'>
				<input class="front_button" id="submit_index" type='submit'>
			</form>
		</div>

		<% if @videos.any? %>
			<% @videos.each do |video| %>
				<% if Track.any? && Track.find_by_youtube_id(video.id.videoId) %>
					<div class="video_thumbnail">
						<a href="videos/<%= video.id['videoId'] %>"><img class='has_tracks' src='<%= video.snippet.thumbnails.medium.url %>'></a>		
						<p><a href="videos/<%= video.id['videoId'] %>"><%= video.snippet.title %></a></p>
					</div>
				<% else %>
					<div class="video_thumbnail">
						<a href="videos/<%= video.id['videoId'] %>"><img src='<%= video.snippet.thumbnails.medium.url %>'></a>		
						<p><a href="videos/<%= video.id['videoId'] %>"><%= video.snippet.title %></a></p>
					</div>
				<% end %>
			<% end  %>
		<% end  %>
	</div>
	<div class="flickr_pagination">
		<%= will_paginate @videos %>
	</div>
</div>